### ISSUE TITLE
Suggestions and feedback

### ISSUE THREAD

**Issue by greyli** [greyli/apiflask#1]
Hi everyone! So happy to finally public this project on the first day of April. I hope this project will make the web API development with Flask a lot easier.

Welcome to leave any ideas or suggestions for this project. I will try to make a beta release as soon as possible.

You can propose any API changes or default value changes. For example:

- Change the default validation status code from 400 to 422.
- Rename the exception `HTTPError` to `HTTPException`.
- A better color for the logo or a better slogan.

If needed, feel free to create a [new issue](https://github.com/greyli/apiflask/issues/new/choose) (for bug/feature/advice/change/improvement) or [new discussion](https://github.com/greyli/apiflask/discussions/new) (for question/discussion/random thoughts).

Thank you! :)

**Comment by sloria** [comment]
Nice work on this! I'm curious to hear about the motivations behind apiflask. What gaps does it fill that existing frameworks don't? I'd be interested to see a comparison with similar projects like apifairy, fastapi, flask-smorest, flask-resty, flask-restx, flask-rebar, etc.
