### ISSUE TITLE
Using empty dict as schema in output decorator causes AttributeError: 'dict' object has no attribute 'many'

### ISSUE THREAD

**Issue by 180909** [greyli/apiflask#11]
code:
`@app.delete('/pets/<int:pet_id>')
@output({}, 204)
def delete_pet(pet_id):
    if pet_id > len(pets) - 1:
        abort_json(404)
    pets.pop(pet_id)
    return ''`
shell:
`curl -v -X DELETE localhost:5000/pets/0`
error:
`AttributeError: 'dict' object has no attribute 'many'`

**Comment by greyli** [comment]
Hi, just fixed this in #12, you can temporarily use EmptySchema to replace the empty dict. See this [commit](https://github.com/greyli/apiflask/pull/12/commits/bd5991de0faed973f3f1430ef9a146804aa9e2fe) for the details.
