### ISSUE TITLE
Can't upload file in Swagger UI

### ISSUE THREAD

**Issue by Farmer-chong** [greyli/apiflask#120]
在apiflask内置的api文档中进行调试时，无法上传文件

demo
```python
from apiflask import APIFlask, input, output, abort
from marshmallow.fields import Raw
app = APIFlask(__name__)

@app.post("/icon")
@input({"icon": Raw(type="file", required=True)}, location="files")
def icon(data):
    print(data.get("icon"))
    return {"ok": 'ok'}
```

在docs页面有正常的选择文件按钮，但观察curl结果发现并没有将选择的文件上传至后端（network中也并没有），但当我使用Postamn等工具进行请求时，后端是正常（结果正常），因此我只能暂时将问题归结于apispec的bug

Environment:

- Python version: 3.7.3
- Flask version: 2.0.1
- APIFlask version: 0.8.0

**Comment by Farmer-chong** [comment]
该问题在HelloFlask中也已抛出 https://discuss.helloflask.com/t/topic/810/3?u=farmer-chong

**Comment by greyli** [comment]
Currently, file uploading is not supported for OpenAPI generating. I just created #123 to continue this issue. Thanks for the feedback!
