### ISSUE TITLE
继承Schema的模板中想排除一些字段，例如：page,pageLimit，发现不支持，是我代码写的有问题么？

### ISSUE THREAD

**Issue by wangzhatian** [greyli/apiflask#166]
from TestFlask.application import db
from TestFlask.module.UserModule import User
from apiflask import Schema
from apiflask.fields import Integer, String

class UserReq(Schema):
    id = Integer(required=True, description="ID"),  # ID
    login_name = Integer(required=True, description="登录名"),  # 登录名
    real_name = String(required=True, description="所属项目")  # 姓名
    branch = String(required=True, description="所属模块")  # 部门
    phone = String(required=True)  # 手机号
    password = String(required=True)  # 密码
    page = Integer(required=True, description="page"),  # page
    pageLimit = Integer(required=True, description="page"),  # pageLimit

    class Meta:
        model = User
        exclude = ["page", "pageLimit"]  # 排除字段列表

if __name__ == '__main__':
    userReq = UserReq()
    print(userReq)

-------------------------->
ValueError: Invalid fields for <UserReq(many=False)>: {'pageLimit', 'page'}.

**Comment by greyli** [comment]
和你自己的代码相关的中文问题请发到 https://discuss.helloflask.com/，并附上上下文代码和问题描述，谢谢。
