### ISSUE TITLE
Consider moving APIFlask back to an extension

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [greyli/apiflask#176]
See this [discussion](https://github.com/pallets/flask/pull/3907#issuecomment-793229391) where Grey says: 

> Glad to see this finally merged! After I proposed this idea and was declined in the first pallets meeting, I started to make the REST API extension I'm developing to become a framework so that I can inherit the Flask class and add these route shortcuts, now I may consider making it back to an extension...

## Motivation

So that we can healthily mix different extensions and not make APIFlask our main point of entry.

**Comment by greyli** [comment]
Route shortcut is not the only reason to make it become a nested framework, I also have to rewrite the Flask class to ensure the natural order of the arguments injected into the view function ([detail](https://apiflask.com/comparison/#a-natural-order-of-view-arguments)).

Do you have any issues when using APIFlask as a framework?

**Comment by greyli** [comment]
Closing it now, feel free to reopen or comment.
