### ISSUE TITLE
when raise a subclass of HTTPError,  message field will be a list

### ISSUE THREAD

**Issue by llt22** [greyli/apiflask#183]
when raise a subclass of HTTPError, the message field will be a list, it's different with when you raise a HTTPError directly

this is a [demo](https://github.com/llt22/apiflask-demo)

I'm not sure it's a bug or feature, but I think it should be consistent
except
```
{
  "detail": {
    
  },
  "message": "This pet is missing."
}
```

current 
```
{
  "detail": {
    
  },
  "message": [
    "This pet is missing."
  ]
}
```

Environment:

- Python version: 3.9
- Flask version: 2.0.2
- APIFlask version: 0.11.0

**Comment by greyli** [comment]
I think this is because you added a comma at the end of the string...

https://github.com/llt22/apiflask-demo/blob/main/main.py#L10

**Comment by llt22** [comment]
> I think this is because you added a comma at the end of the string...
> 
> https://github.com/llt22/apiflask-demo/blob/main/main.py#L10

sorry!!!
