### ISSUE TITLE
Support using external authentication library

### ISSUE THREAD

**Issue by greyli** [greyli/apiflask#186]
Add a way to register an external authentication library for `@auth_required`.

**Comment by imoyao** [comment]
I have seen some activities on my timeline and noticed you starred the project [flask-jwt-extended](https://github.com/vimalloc/flask-jwt-extended), and i found a useful extension like this named [flask-praetorian ](https://flask-praetorian.readthedocs.io/en/latest/index.html),as the document said:

> The flask-praetorian package can be used to:
>
> - Hash passwords for storing in your database
> - Verify plain text passwords against the hashed, stored versions
> - Generate authorization tokens upon verification of passwords
> - Check requests to secured endpoints for authorized tokens
> - Supply expiration of tokens and mechanisms for refreshing them
> - Ensure that the users associated with tokens have necessary roles for access
> - Parse user information from request headers or cookies for use in client route handlers
> - Support inclusion of custom user claims in tokens
> - Register new users using email verification
> 
>  All of this is provided in a very simple to confiure and initialize flask extension. Though simple, the security provided by flask-praetorian is strong due to the usage of the proven security technology of JWT and python’s PassLib package.

It is worth noting that the author have a comparison with [flask-jwt-extended](https://flask-praetorian.readthedocs.io/en/latest/comparison.html#flask-jwt-extended)！Maybe it can help you somewhere? (perhaps it will be low priority.)

**Comment by greyli** [comment]
@imoyao Thanks for the recommdation. It's looks like a great project.

I'm not going to integrate more extensions in APIFlask (I just want to find a way to support user to use different auth extension, then generate the security section of the OpenAPI spec for these auth extentions), but I may mention it in docs in the future.
