### ISSUE TITLE
About swagger built-in resource reference CDN problem

### ISSUE THREAD

**Issue by Farmer-chong** [greyli/apiflask#216]
The current swagger built-in resources are referenced from the jsdelivr site
Due to domestic network problems, the docs page cannot be opened.

当前`/docs`页面资源使用了**jsdelivr**站点提供的CDN服务，而该站点由于被墙导致页面无法正常显示

**Comment by greyli** [comment]
Is the issue still exist? I can reach these files on my side (Shanghai) without the VPN.

A simple workaround for this would be [using the related configuration variables to set a custom CDN provider](https://apiflask.com/api-docs/#use-different-cnd-server-for-swagger-uiredoc-resources).

**Comment by Farmer-chong** [comment]
This problem does not exist for the time being, but after many days of observation and the feedback from other users, the problem will occur from time to time
