### ISSUE TITLE
RFC: Import fields from Marshmallow selectively and remove some aliases

### ISSUE THREAD

**Issue by greyli** [greyli/apiflask#63]
Marshmallow provides some aliases for one field, for example, `Str` and `String`. To keep everything simple and consistent, I imported the fields selectively in `apiflask.fields`, so the IDE will not prompt `Url` and `URL` when you type "U". The following aliases were removed:

- Str
- Int
- Bool
- Url
- UrlFor
- AbsoluteUrlFor

Instead, you will need to use:

- String
- Integer
- Boolean
- URL
- URLFor
- AbsoluteURLFor

Users can still import all the fields from Marshmallow, I will address this change in the docs.

Is it a good or bad idea? Feel free to leave any thoughts.

**Comment by lafrech** [comment]
Pros:

- IDE will not prompt Url and URL when you type "U"
- ?

Cons:

- Need to update APIFlask every time marshmallow adds a field
- Potentially surprising for users who know marshmallow fields

This adds a thin layer for little benefit IMHO. I wouldn't engage into this if I were you.

You could, however, open an issue in marshmallow bugtracker to discuss the usefulness of aliases.

There's nothing specific to APIFlask, here. The code completion issue is common with marshmallow. I'd address this at marshmallow level and follow the consensus.

**Comment by greyli** [comment]
Thanks to @lafrech for the advice. I decided to keep this change in the 1.0 version.

The future discussion will happen at https://github.com/marshmallow-code/marshmallow/issues/1828.
